spring:
  profiles: alpha
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/user/**
      url: http://localhost:8080
    pay:
      stripPrefix: false
      path: /v1/pay/**
      url: http://localhost:8081
    else:
      stripPrefix: false
      path: /v1/**
      url: http://localhost:8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true #서비스간 통신 시 hostname보다 ip 를 우선 사용하도록 설정.
