spring:
  profiles: local
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/user/**
      serviceId: user-service
    pay:
      stripPrefix: false
      path: /v1/pay/**
      serviceId: book-service
    else:
      stripPrefix: false
      path: /v1/**
      serviceId: book-service
